version: 2

references:

  ubuntu_install: &ubuntu_install
    run:
      name: Install dependencies on Ubuntu.
      command: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -qy
        apt-get install -y git python3-dev python3-pip curl
        pip3 install .

  install: &install
    run:
      name: Install dependencies and shepherd on Archlinux
      command: |
        set -x
        VER="17.11.0-ce"
        curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/test/x86_64/docker-$VER.tgz
        tar -xz -C /tmp -f /tmp/docker-$VER.tgz
        pacman --noconfirm --needed -Syu minio python-pip python-babel python-click python-matplotlib python-numpy python-requests python-ruamel-yaml python-testfixtures python-tabulate
        pip install --no-cache-dir git+https://github.com/iterait/emloop.git
        mkdir examples/docker/emloop_example/ssh
        pip install .
        pip install '.[tests]'
        pip freeze

  add_rw_key: &add_rw_key
    add_ssh_keys:
      fingerprints:
        - "bd:18:69:44:c4:97:94:f2:03:ba:db:dd:29:2e:cf:f2"

  # non-root user is added so that file-related permission denied can happen and be properly tested
  test: &test
    run:
      name: Run tests.
      command: |
        PATH=$PATH:/tmp/docker
        useradd -m -s /bin/bash test
        passwd -d test
        chown -R test /root
        sudo -u test pytest -v

  doc: &doc
    run:
      name: Generate documentation
      command: |
        pip3 install '.[docs]'
        bash <(curl -fsSL https://raw.githubusercontent.com/iterait/ci-utils/master/doc_deploy.sh)

jobs:

  test_archlinux:
    docker:
      - image: iterait/archlinux
    working_directory: ~/shepherd
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.11.0-ce
      - checkout
      - *install
      - *test

  generate_documentation:
    docker:
      - image: ubuntu:rolling
    working_directory: ~/shepherd
    steps:
      - checkout
      - *ubuntu_install
      - *add_rw_key
      - *doc

workflows:
  version: 2
  test:
    jobs:
      - test_archlinux:
          filters:
            branches:
              ignore:
                - gh-pages
      - generate_documentation:
          filters:
            branches:
              only: dev
          requires:
            - test_archlinux

  nightly-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - dev
    jobs:
      - test_archlinux
